### ISSUE TITLE
Composer install error with symfony 4

### ISSUE THREAD

**Issue by zoomtronic** [jorisdugue/h5p-bundle#1]
Hi !

It's not possible to install this bundle on a Symfony 4 project because you set in your composer.json the "symfony/serializer" to match version 5.0 and not >=4.4.

Cheers,

**Comment by zoomtronic** [comment]
Hi again,

I saw you modified the composer.json but composer still say 
`jorisdugue/h5p-bundle v1.1.0 requires symfony/serializer ^5.0 -> no matching package found.`

when composer require jorisdugue/h5p-bundle :(

**Comment by zoomtronic** [comment]
I've made a fork and composer succesfully install the bundle with these parameters

`"symfony/framework-bundle": "4.4.*",
        "symfony/serializer": "4.4.*",`

**Comment by jorisdugue** [comment]
Hello,

I fixed the problem in the branch master I deploy in a new version (https://packagist.org/packages/jorisdugue/h5p-bundle#v1.2.0)
