### ISSUE TITLE
Call to a member function fetchAll() on bool

### ISSUE THREAD

**Issue by tuxes3** [jorisdugue/h5p-bundle#40]
## Where:

`/h5p/ajax/content-type-cache/?`

## Error:

`Call to a member function fetchAll() on bool`

## Solution:

https://github.com/jorisdugue/h5p-bundle/blob/master/Entity/LibraryRepository.php#L79

```
NO:
$stmt = $stmt->execute();

YES:
$stmt->execute();
```

**Comment by jorisdugue** [comment]
Hey @tuxes3,
Thanks for this report i didnt see last time with this have been updated.
