### ISSUE TITLE
Call to a member function getUser() on null

### ISSUE THREAD

**Issue by bwebdevro** [jorisdugue/h5p-bundle#46]
Hi!

I have installed the bundle in a clean Symfony 6.1.12 environment, but when I try to access the path `/h5p/new` I get the following error:
`Call a member function getUser() on null`.
Is this package required to have user registration logic?
I did not find this in the documentation.

Thank you!

**Comment by jorisdugue** [comment]
Hey @bwebdevro,

You are absolutely right, you need to have a user entity to be able to manipulate the different routes. During the last update by @tuxes3 some modifications were made to take into account certain changes in symfony 6

So you need to have a base entity with a user to be able to use the base bundle. We have not committed a user entity to avoid any conflict with the base user. However, we have made several references to the logged in user. basic under symfony

**Comment by tuxes3** [comment]
@bwebdevro 

best case would be to allow nullable in all cases a User is asked for. I am happy to review if you publish a PR!

**Comment by jorisdugue** [comment]
This may cause problems on some routes if the user is not present. Some routes require at least the user ID to work (for example stats) but actually it can be interesting not necessarily to be linked to a user in some because it may be necessary to provide a system of alternative identifier? 🤔

**Comment by tuxes3** [comment]
all should work with the symfony provided "UserInterface". If not given we could maybe work with an anonymous Token / Session Id. As said, im happy to review, sadly i am mot able to publish any more work the next few weeks.

**Comment by bwebdevro** [comment]
Thank you for the response. It worked after adding UserInterface, but left also the case if the User is null
