### ISSUE TITLE
some changes not in the latest tag

### ISSUE THREAD

**Issue by michealmouner** [jorisdugue/h5p-bundle#5]
Resources/config/routes.yaml:2

last tag version `1.3.1` doesn't include this change 
from
`resource: "@StuditH5PBundle/Controller/H5PAjaxController.php"`
to
`resource: "@StuditH5PBundle/Controller/H5PAJAXController.php"`

this cause a problem in Linux os 

plz create a new tag

**Comment by jorisdugue** [comment]
Hello,
I just created the tag that was missing his tag is 1.4.0

**Comment by michealmouner** [comment]
> Hello,
> I just created the tag that was missing his tag is 1.4.0

thank you
