### ISSUE TITLE
truncate postgresql table

### ISSUE THREAD

**Issue by bpetitcollot** [jorisdugue/h5p-bundle#50]
Hello,
i have tried to use this bundle with a postgresql database but H5PSymfony threw an error when trying to truncate tables because of SET FOREIGN_KEY_CHECKS which does not exist in posrgre.

One solution would be to test database platform before executing this statement.

Even better would be to switch private methods of services to protected so that we could override them in our app.

**Comment by jorisdugue** [comment]
Hi @bpetitcollot,

This issue has been resolved 😄. I wrote the equivalent of foreign keys for postgresql

Thank you for reporting this bug, don't hesitate if you see another problem in the project

**Comment by jorisdugue** [comment]
this is now available in v2.1.0 : 
- https://github.com/jorisdugue/h5p-bundle/releases/tag/v2.1.0
